last_change = 2026-08-15T07:57:08.462234Z
addr = 0x151520
size = 0x9
name = "CBaseEntity_GetChangeAccessorPathInfo_2"

[header]
name = "CBaseEntity_GetChangeAccessorPathInfo_2"
addr = 0x151520

[header.args]
