last_change = 2026-08-18T05:10:31.197796Z
addr = 0x159120
size = 0x3
name = "IGameSystem_OnServerBeginAsyncPostTickWork"

[header]
name = "IGameSystem_OnServerBeginAsyncPostTickWork"
addr = 0x159120

[header.args]
