last_change = 2026-08-18T05:10:31.197742Z
addr = 0x150d20
size = 0x3
name = "IGameSystem_OnServerPostEntityThink"

[header]
name = "IGameSystem_OnServerPostEntityThink"
addr = 0x150d20

[header.args]
