last_change = 2026-08-18T05:10:43.369252Z
addr = 0x1eefd0
size = 0x688
name = "CDedicatedServerWorkshopManager_SwitchToWorkshopMapGroup"
type = "long long"

[header]
name = "CDedicatedServerWorkshopManager_SwitchToWorkshopMapGroup"
addr = 0x1eefd0
type = "long long"

[header.args]
