last_change = 2026-08-15T07:57:20.536362Z
addr = 0x25fa70
size = 0x2de
name = "ScriptBinding_Entity_SetEntityName"
type = "void"

[header]
name = "ScriptBinding_Entity_SetEntityName"
addr = 0x25fa70
type = "void"

[header.args]
