last_change = 2026-08-15T07:57:20.580264Z
addr = 0x260a00
size = 0x2f5
name = "ScriptBinding_CBaseModelEntity_SetModel"
type = "void"

[header]
name = "ScriptBinding_CBaseModelEntity_SetModel"
addr = 0x260a00
type = "void"

[header.args]
