last_change = 2026-08-15T07:57:08.462458Z
addr = 0x3cabe0
size = 0x2c5
name = "CBaseEntity_ModifyOrAppendCriteria"
type = "long long"

[header]
name = "CBaseEntity_ModifyOrAppendCriteria"
addr = 0x3cabe0
type = "long long"

[header.args]
