last_change = 2026-08-18T05:10:45.903983Z
addr = 0x52d070
size = 0x4b
name = "IGameSystem_ShutdownAllSystems"
type = "long long"

[header]
name = "IGameSystem_ShutdownAllSystems"
addr = 0x52d070
type = "long long"

[header.args]
