last_change = 2026-08-18T05:10:31.198726Z
addr = 0x60fb10
size = 0x33
name = "CBaseModelEntity_ScriptSetSingleMeshGroup"

[header]
name = "CBaseModelEntity_ScriptSetSingleMeshGroup"
addr = 0x60fb10

[header.args]
