last_change = 2026-08-16T09:31:40.250546Z
addr = 0x60dfa0
size = 0x2e4
name = "CNetworkUtlVectorEmbedded_TryLateResolve_m_vecRenderAttributes"
type = "char"

[header]
name = "CNetworkUtlVectorEmbedded_TryLateResolve_m_vecRenderAttributes"
addr = 0x60dfa0
type = "char"

[header.args]
