last_change = 2026-08-18T05:10:46.878862Z
addr = 0x60dfa0
size = 0x2e4
name = "CNetworkUtlVectorEmbedded_TryLateResolve_m_vecRenderAttributes"
type = "char"

[header]
name = "CNetworkUtlVectorEmbedded_TryLateResolve_m_vecRenderAttributes"
addr = 0x60dfa0
type = "char"

[header.args]
