last_change = 2026-08-16T09:31:42.587408Z
addr = 0x8ce9e0
size = 0xdbb
name = "CCSGameRules_GoToIntermission"
type = "void"

[header]
name = "CCSGameRules_GoToIntermission"
addr = 0x8ce9e0
type = "void"

[header.args]
