last_change = 2026-08-15T07:57:08.462670Z
addr = 0x8f2690
size = 0x2e9
name = "CCSGameRules_PlayerSpawn"
type = "long long"

[header]
name = "CCSGameRules_PlayerSpawn"
addr = 0x8f2690
type = "long long"

[header.args]
