last_change = 2026-08-16T09:31:42.742220Z
addr = 0x9031b0
size = 0x16b4
name = "CCSGameRules_TerminateRound"
type = "char *"

[header]
name = "CCSGameRules_TerminateRound"
addr = 0x9031b0
type = "char *"

[header.args]
