last_change = 2026-08-15T07:57:08.462688Z
addr = 0x97cc90
size = 0x41
name = "SV_Kill_SmokeGrenade_CommandHandler"
type = "long long"

[header]
name = "SV_Kill_SmokeGrenade_CommandHandler"
addr = 0x97cc90
type = "long long"

[header.args]
