last_change = 2026-08-16T09:31:23.750008Z
addr = 0x97cc90
size = 0x41
name = "SV_Kill_SmokeGrenade_CommandHandler"
type = "void"

[header]
name = "SV_Kill_SmokeGrenade_CommandHandler"
addr = 0x97cc90
type = "void"

[header.args]
