last_change = 2026-08-15T07:57:26.476479Z
addr = 0xa1f1a0
size = 0xb67
name = "CBasePlayerController_HandleCommand_JoinTeam"
type = "char"

[header]
name = "CBasePlayerController_HandleCommand_JoinTeam"
addr = 0xa1f1a0
type = "char"

[header.args]
