last_change = 2026-08-15T07:57:08.462708Z
addr = 0xa28f00
size = 0xc
name = "CCSPlayerController_InventoryUpdateThink"
type = "long long"

[header]
name = "CCSPlayerController_InventoryUpdateThink"
addr = 0xa28f00
type = "long long"

[header.args]
