last_change = 2026-08-15T07:57:08.462713Z
addr = 0xa38350
size = 0x40
name = "CCSPlayerController_HandleCommandDrop"
type = "char"

[header]
name = "CCSPlayerController_HandleCommandDrop"
addr = 0xa38350
type = "char"

[header.args]
