last_change = 2026-08-16T09:31:23.750106Z
addr = 0xa59fb0
size = 0x735
name = "GiveNamedItem"
type = "unsigned long long *"

[header]
name = "GiveNamedItem"
addr = 0xa59fb0
type = "unsigned long long *"

[header.args]
