last_change = 2026-08-18T05:10:50.342800Z
addr = 0xa68b40
size = 0x7e1
name = "CCSPlayer_ItemServices_GiveDefaultItems"
type = "void"

[header]
name = "CCSPlayer_ItemServices_GiveDefaultItems"
addr = 0xa68b40
type = "void"

[header.args]
