last_change = 2026-08-16T09:31:23.750213Z
addr = 0xa8ab20
size = 0x70b
name = "CCSPlayer_UseServices_BumpWeapon"
type = "char"

[header]
name = "CCSPlayer_UseServices_BumpWeapon"
addr = 0xa8ab20
type = "char"

[header.args]
