last_change = 2026-08-15T07:57:08.462769Z
addr = 0xaabe70
size = 0x39f
name = "CCSPlayer_WeaponServices_HandleDropWeapon"
type = "char"

[header]
name = "CCSPlayer_WeaponServices_HandleDropWeapon"
addr = 0xaabe70
type = "char"

[header.args]
