last_change = 2026-08-15T07:57:08.462781Z
addr = 0xaebfd0
size = 0x5
name = "CCSPlayerController_ResetForceTeamThink"
type = "long long"

[header]
name = "CCSPlayerController_ResetForceTeamThink"
addr = 0xaebfd0
type = "long long"

[header.args]
