last_change = 2026-08-15T07:57:08.462796Z
addr = 0xaf19b0
size = 0x5f
name = "CBasePlayerController_GetPawn"
type = "long long"

[header]
name = "CBasePlayerController_GetPawn"
addr = 0xaf19b0
type = "long long"

[header.args]
