last_change = 2026-08-16T09:31:45.752328Z
addr = 0xb0fe40
size = 0x318
name = "CBasePlayerController_SetConnectedState"
type = "long long"

[header]
name = "CBasePlayerController_SetConnectedState"
addr = 0xb0fe40
type = "long long"

[header.args]
