last_change = 2026-08-15T07:57:08.462840Z
addr = 0xb58f20
size = 0x22e
name = "CEntitySaveRestoreBlockHandler_PreSave"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_PreSave"
addr = 0xb58f20
type = "long long"

[header.args]
