last_change = 2026-08-16T09:31:23.750440Z
addr = 0xb58f20
size = 0x22e
name = "CEntitySaveRestoreBlockHandler_PreSave"
type = "char"

[header]
name = "CEntitySaveRestoreBlockHandler_PreSave"
addr = 0xb58f20
type = "char"

[header.args]
