last_change = 2026-08-15T07:57:08.462838Z
addr = 0xb57c50
size = 0x5
name = "CGameSystemReallocatingFactory_CSource2EntitySystem_Init"

[header]
name = "CGameSystemReallocatingFactory_CSource2EntitySystem_Init"
addr = 0xb57c50

[header.args]
