last_change = 2026-08-16T09:31:46.795273Z
addr = 0xb7ea10
size = 0x216
name = "CLoadingSpawnGroup_CreateEntityToSpawn"
type = "long long"

[header]
name = "CLoadingSpawnGroup_CreateEntityToSpawn"
addr = 0xb7ea10
type = "long long"

[header.args]
