last_change = 2026-08-15T07:57:08.462880Z
addr = 0xb7ec30
size = 0x9a4
name = "CreateEntityTransitionList"
type = "long long"

[header]
name = "CreateEntityTransitionList"
addr = 0xb7ec30
type = "long long"

[header.args]
