last_change = 2026-08-15T07:57:08.462882Z
addr = 0xb83750
size = 0x158
name = "CEntitySaveRestoreBlockHandler_DoRestoreEntity"
type = "bool"

[header]
name = "CEntitySaveRestoreBlockHandler_DoRestoreEntity"
addr = 0xb83750
type = "bool"

[header.args]
