last_change = 2026-08-15T07:57:08.462901Z
addr = 0xba0f40
size = 0x99
name = "CGameEntitySystem_OnAddEntity"
type = "long long"

[header]
name = "CGameEntitySystem_OnAddEntity"
addr = 0xba0f40
type = "long long"

[header.args]
