last_change = 2026-08-16T09:31:48.770037Z
addr = 0xbdfbb0
size = 0x12eb
name = "CLoopModeGame_LoopInit"
type = "char"

[header]
name = "CLoopModeGame_LoopInit"
addr = 0xbdfbb0
type = "char"

[header.args]
