last_change = 2026-08-15T07:57:08.463026Z
addr = 0xc2e580
size = 0xc1
name = "CBaseEntity_DispatchSpawn"
type = "long long"

[header]
name = "CBaseEntity_DispatchSpawn"
addr = 0xc2e580
type = "long long"

[header.args]
