last_change = 2026-08-16T09:31:50.079770Z
addr = 0xc4e860
size = 0x84d
name = "CBaseEntity_ctor"
type = "long long"

[header]
name = "CBaseEntity_ctor"
addr = 0xc4e860
type = "long long"

[header.args]
