last_change = 2026-08-18T05:10:31.199873Z
addr = 0xc7cd90
size = 0x3c
name = "CBaseEntity_ScriptGetRootMoveParent"

[header]
name = "CBaseEntity_ScriptGetRootMoveParent"
addr = 0xc7cd90

[header.args]
