last_change = 2026-08-16T09:31:23.751099Z
addr = 0xc769c0
size = 0x1f9
name = "CBaseEntity_OnSetDormant"
type = "double"

[header]
name = "CBaseEntity_OnSetDormant"
addr = 0xc769c0
type = "double"

[header.args]
