last_change = 2026-08-15T07:57:08.463171Z
addr = 0xd1b3e0
size = 0x19
name = "CSource2Server_ShouldTimeoutClient"
type = "char"

[header]
name = "CSource2Server_ShouldTimeoutClient"
addr = 0xd1b3e0
type = "char"

[header.args]
