last_change = 2026-08-15T07:57:34.922500Z
addr = 0xd1ac30
size = 0xbb
name = "CSource2Server_GetLevelsFromSaveFile"
type = "void"

[header]
name = "CSource2Server_GetLevelsFromSaveFile"
addr = 0xd1ac30
type = "void"

[header.args]
