last_change = 2026-08-15T07:57:08.463157Z
addr = 0xd1a810
size = 0xb4
name = "CSource2Server_Shutdown"
type = "long long"

[header]
name = "CSource2Server_Shutdown"
addr = 0xd1a810
type = "long long"

[header.args]
