last_change = 2026-08-16T09:31:52.534028Z
addr = 0xd1ac30
size = 0xbb
name = "CSource2Server_GetLevelsFromSaveFile"
type = "void"

[header]
name = "CSource2Server_GetLevelsFromSaveFile"
addr = 0xd1ac30
type = "void"

[header.args]
