last_change = 2026-08-18T05:10:59.849886Z
addr = 0xd2edb0
size = 0x89b
name = "CSource2GameClients_ProcessUsercmds"
type = "long long"

[header]
name = "CSource2GameClients_ProcessUsercmds"
addr = 0xd2edb0
type = "long long"

[header.args]
