last_change = 2026-08-18T05:11:00.071363Z
addr = 0xd61fc0
size = 0x195
name = "CMultiplayRules_ctor"
type = "unsigned long long *"

[header]
name = "CMultiplayRules_ctor"
addr = 0xd61fc0
type = "unsigned long long *"

[header.args]
