last_change = 2026-08-16T09:31:23.751552Z
addr = 0xd6a9b0
size = 0x71
name = "CMultiplayRules_ClientDisconnected"
type = "void"

[header]
name = "CMultiplayRules_ClientDisconnected"
addr = 0xd6a9b0
type = "void"

[header.args]
