last_change = 2026-08-16T09:31:23.751584Z
addr = 0xd95640
size = 0xf6
name = "CBaseEntity_VPhysicsStartTouch"
type = "double"

[header]
name = "CBaseEntity_VPhysicsStartTouch"
addr = 0xd95640
type = "double"

[header.args]
