last_change = 2026-08-15T07:57:08.463255Z
addr = 0xd95640
size = 0xf6
name = "CBaseEntity_VPhysicsStartTouch"
type = "long long"

[header]
name = "CBaseEntity_VPhysicsStartTouch"
addr = 0xd95640
type = "long long"

[header.args]
