last_change = 2026-08-16T09:31:23.751606Z
addr = 0xdb1cd0
size = 0x5ea
name = "CPointTeleportAPI_TeleportEntityInternal"
type = "unsigned long long *"

[header]
name = "CPointTeleportAPI_TeleportEntityInternal"
addr = 0xdb1cd0
type = "unsigned long long *"

[header.args]
