last_change = 2026-08-16T09:31:23.751651Z
addr = 0xe895b0
size = 0x36
name = "CTriggerGravity_GetTouchFunction"
type = "double (__fastcall *)(long long, long long)"

[header]
name = "CTriggerGravity_GetTouchFunction"
addr = 0xe895b0
type = "double (__fastcall *)(long long, long long)"

[header.args]
