last_change = 2026-08-15T07:57:08.463292Z
addr = 0xea4df0
size = 0x9e
name = "UTIL_ClientPrintAll"
type = "long long"

[header]
name = "UTIL_ClientPrintAll"
addr = 0xea4df0
type = "long long"

[header.args]
