last_change = 2026-08-15T07:57:08.463305Z
addr = 0x121c9c0
size = 0x4d9
name = "CEntitySystem_ctor"
type = "long long"

[header]
name = "CEntitySystem_ctor"
addr = 0x121c9c0
type = "long long"

[header.args]
