last_change = 2026-08-16T09:31:55.534903Z
addr = 0x121dde0
size = 0x205
name = "CEntitySystem_AddEntityIOEventToQueue"
type = "void"

[header]
name = "CEntitySystem_AddEntityIOEventToQueue"
addr = 0x121dde0
type = "void"

[header.args]
