last_change = 2026-08-18T05:11:01.659403Z
addr = 0x121eba0
size = 0x279
name = "CEntitySystem_AddEntityToNameMap"
type = "void"

[header]
name = "CEntitySystem_AddEntityToNameMap"
addr = 0x121eba0
type = "void"

[header.args]
