last_change = 2026-08-16T09:31:23.751729Z
addr = 0x121dff0
size = 0x277
name = "CEntitySystem_AddEntityIOEvent"
type = "void"

[header]
name = "CEntitySystem_AddEntityIOEvent"
addr = 0x121dff0
type = "void"

[header.args]
