last_change = 2026-08-15T07:57:08.463347Z
addr = 0x1226240
size = 0x36b
name = "CEntitySystem_ExecuteQueuedSetInPVS"
type = "void"

[header]
name = "CEntitySystem_ExecuteQueuedSetInPVS"
addr = 0x1226240
type = "void"

[header.args]
