last_change = 2026-08-15T07:57:08.463353Z
addr = 0x1227cd0
size = 0x2c
name = "CEntitySystem_ForceSetInPVSCallsIntoQueue"
type = "long long"

[header]
name = "CEntitySystem_ForceSetInPVSCallsIntoQueue"
addr = 0x1227cd0
type = "long long"

[header.args]
