last_change = 2026-08-18T05:11:03.026645Z
addr = 0x122cb40
size = 0x7f
name = "CEntitySystem_PostDataUpdate"
type = "long long"

[header]
name = "CEntitySystem_PostDataUpdate"
addr = 0x122cb40
type = "long long"

[header.args]
