last_change = 2026-08-15T07:57:08.463328Z
addr = 0x1222060
size = 0x12f
name = "CEntitySystem_CreateEntityByName"
type = "long long"

[header]
name = "CEntitySystem_CreateEntityByName"
addr = 0x1222060
type = "long long"

[header.args]
