last_change = 2026-08-15T07:57:08.463359Z
addr = 0x1228710
size = 0x5d9
name = "CEntitySystem_HelperExecuteQueuedSpawn"
type = "int"

[header]
name = "CEntitySystem_HelperExecuteQueuedSpawn"
addr = 0x1228710
type = "int"

[header.args]
