last_change = 2026-08-18T05:11:03.249659Z
addr = 0x12320d0
size = 0x25a
name = "CEntitySystem_SetInPVS"
type = "void"

[header]
name = "CEntitySystem_SetInPVS"
addr = 0x12320d0
type = "void"

[header.args]
