last_change = 2026-08-18T05:11:03.820749Z
addr = 0x1243eb0
size = 0x1c3
name = "CBaseEntity_ReloadPrivateScripts"
type = "void"

[header]
name = "CBaseEntity_ReloadPrivateScripts"
addr = 0x1243eb0
type = "void"

[header.args]
