last_change = 2026-08-16T09:31:23.752131Z
addr = 0x1246cf0
size = 0x12d
name = "CEntityIdentity_SetEntityName"
type = "void"

[header]
name = "CEntityIdentity_SetEntityName"
addr = 0x1246cf0
type = "void"

[header.args]
