last_change = 2026-08-18T05:11:04.126380Z
addr = 0x1245900
size = 0x433
name = "CEntityIdentity_AcceptInputInternal"
type = "char"

[header]
name = "CEntityIdentity_AcceptInputInternal"
addr = 0x1245900
type = "char"

[header.args]
