[0x1c5635]
addr = 0x1c5635
func_addr = 0x1c5570
comment = "Trap to Debugger"
decompiled = false

[0x1c5643]
addr = 0x1c5643
func_addr = 0x1c5570
comment = "Trap to Debugger"
decompiled = false

[0x1c5656]
addr = 0x1c5656
func_addr = 0x1c5570
comment = "Trap to Debugger"
decompiled = false

[0x1ccd92]
addr = 0x1ccd92
func_addr = 0x1cb900
comment = "void (__cdecl *)()"
decompiled = false

[0x1ef3eb]
addr = 0x1ef3eb
func_addr = 0x1eefd0
comment = "Trap to Debugger"
decompiled = false

[0x225d51]
addr = 0x225d51
func_addr = 0x225cf0
comment = "struct v8::Isolate *"
decompiled = false

[0x225d54]
addr = 0x225d54
func_addr = 0x225cf0
comment = "this"
decompiled = false

[0x225d8f]
addr = 0x225d8f
func_addr = 0x225cf0
comment = "this"
decompiled = false

[0x225dbe]
addr = 0x225dbe
func_addr = 0x225cf0
comment = "int"
decompiled = false

[0x225dc0]
addr = 0x225dc0
func_addr = 0x225cf0
comment = "this"
decompiled = false

[0x225dfc]
addr = 0x225dfc
func_addr = 0x225cf0
comment = "int"
decompiled = false

[0x225e01]
addr = 0x225e01
func_addr = 0x225cf0
comment = "this"
decompiled = false

[0x225fa3]
addr = 0x225fa3
func_addr = 0x225cf0
comment = "this"
decompiled = false

[0x25fad1]
addr = 0x25fad1
func_addr = 0x25fa70
comment = "struct v8::Isolate *"
decompiled = false

[0x25fad4]
addr = 0x25fad4
func_addr = 0x25fa70
comment = "this"
decompiled = false

[0x25fb0f]
addr = 0x25fb0f
func_addr = 0x25fa70
comment = "this"
decompiled = false

[0x25fb3e]
addr = 0x25fb3e
func_addr = 0x25fa70
comment = "int"
decompiled = false

[0x25fb40]
addr = 0x25fb40
func_addr = 0x25fa70
comment = "this"
decompiled = false
