[0x15d2400]
last_change = 2026-08-17T02:59:27.279609Z
addr = 0x15d2400
name = "V_stricmp_fast"
type = "long long __fastcall(unsigned long long, unsigned long long)"
size = 0x8

[0x190e630]
addr = 0x190e630
name = "g_pInterfaceGlobals"
size = 0x8

[0x1bc7670]
addr = 0x1bc7670
name = "qword_181BC8670"
size = 0x8

[0x1becb48]
addr = 0x1becb48
name = "IGameSystem_LoopDestroyAllSystems_s_GameSystems"
size = 0x4

[0x1c52d18]
addr = 0x1c52d18
name = "g_GameTraceManager"
size = 0x8

[0x1c530f0]
addr = 0x1c530f0
name = "gameeventmanager"
size = 0x8

[0x1c53320]
addr = 0x1c53320
name = "s_GameEventManager"
size = 0x8

[0x1da0e08]
addr = 0x1da0e08
name = "g_pEntityList"
size = 0x8

[0x1dffdf8]
addr = 0x1dffdf8
name = "g_pCSBotManager"
size = 0x8

[0x1e453a0]
addr = 0x1e453a0
name = "IGameSystem_LoopPostInitAllSystems_pEventDispatcher"
size = 0x8

[0x1e453b8]
addr = 0x1e453b8
name = "IGameSystem_InitAllSystems_pFirst"
size = 0x8

[0x1e45428]
addr = 0x1e45428
name = "g_EntitySystem"
size = 0x8

[0x1f61768]
addr = 0x1f61768
name = "CCSGameRules__sm_mapGcBanInformation"
size = 0x1

[0x1f6dd20]
addr = 0x1f6dd20
name = "g_pGameTypes"
size = 0x8

[0x1fc4060]
addr = 0x1fc4060
name = "g_pGameEntitySystem"
size = 0x8

[0x1fcd6b8]
addr = 0x1fcd6b8
name = "CPlayer_MovementServices_s_pRunCommandPawn"
size = 0x8

[0x1fe5bc0]
addr = 0x1fe5bc0
name = "g_networkstringtable"
size = 0x8

[0x1fe5db0]
addr = 0x1fe5db0
name = "g_engine"
size = 0x8

[0x1fe5db8]
addr = 0x1fe5db8
name = "g_pGameRules"
size = 0x8
