[0x15d2400]
last_change = 2026-08-17T02:59:27.279609Z
addr = 0x15d2400
name = "V_stricmp_fast"
type = "long long __fastcall(unsigned long long, unsigned long long)"
size = 0x8

[0x190e630]
addr = 0x190e630
name = "g_pInterfaceGlobals"
size = 0x8

[0x1bc7670]
addr = 0x1bc7670
name = "qword_181BC8670"
size = 0x8

[0x1becb48]
addr = 0x1becb48
name = "IGameSystem_LoopDestroyAllSystems_s_GameSystems"
size = 0x4

[0x1c52d18]
addr = 0x1c52d18
name = "g_GameTraceManager"
size = 0x8

[0x1c530f0]
addr = 0x1c530f0
name = "gameeventmanager"
size = 0x8

[0x1c53320]
addr = 0x1c53320
name = "s_GameEventManager"
size = 0x8

[0x1da0e08]
addr = 0x1da0e08
name = "g_pEntityList"
size = 0x8

[0x1dffdf8]
addr = 0x1dffdf8
name = "g_pCSBotManager"
size = 0x8

[0x1e453a0]
addr = 0x1e453a0
name = "IGameSystem_LoopPostInitAllSystems_pEventDispatcher"
size = 0x8

[0x1e453b8]
addr = 0x1e453b8
name = "IGameSystem_InitAllSystems_pFirst"
size = 0x8

[0x1e45428]
addr = 0x1e45428
name = "g_EntitySystem"
size = 0x8

[0x1f61768]
addr = 0x1f61768
name = "CCSGameRules__sm_mapGcBanInformation"
size = 0x1

[0x1f6dd20]
addr = 0x1f6dd20
name = "g_pGameTypes"
size = 0x8

[0x1fc4060]
addr = 0x1fc4060
name = "g_pGameEntitySystem"
size = 0x8

[0x1fcd6b8]
addr = 0x1fcd6b8
name = "CPlayer_MovementServices_s_pRunCommandPawn"
size = 0x8

[0x1fe5bc0]
addr = 0x1fe5bc0
name = "g_networkstringtable"
size = 0x8

[0x1fe5db0]
addr = 0x1fe5db0
name = "g_engine"
size = 0x8

[0x1fe5db8]
addr = 0x1fe5db8
name = "g_pGameRules"
size = 0x8

[0x21347c0]
addr = 0x21347c0
name = "g_pEntitySystem"
size = 0x8

[0x2137d28]
addr = 0x2137d28
name = "g_pGameResourceService"
size = 0x8

[0x214b7d8]
addr = 0x214b7d8
name = "g_pNavMesh"
size = 0x8

[0x21a4b50]
addr = 0x21a4b50
name = "g_pVApplication"
size = 0x8

[0x21a4b58]
addr = 0x21a4b58
name = "g_pVEngineCvar"
size = 0x8

[0x21a4b60]
addr = 0x21a4b60
name = "g_pVStringTokenSystem"
size = 0x8

[0x21a4b68]
addr = 0x21a4b68
name = "g_pProcessUtils"
size = 0x8

[0x21a4b70]
addr = 0x21a4b70
name = "g_pHelpSystem"
size = 0x1

[0x21a4b78]
addr = 0x21a4b78
name = "g_pToolSceneNodeFactory"
size = 0x1

[0x21a4b80]
addr = 0x21a4b80
name = "g_pEconItemToolModel"
size = 0x1

[0x21a4b88]
addr = 0x21a4b88
name = "g_pSchemaTestExternalTwo"
size = 0x1

[0x21a4b90]
addr = 0x21a4b90
name = "g_pSchemaTestExternalOne"
size = 0x1

[0x21a4b98]
addr = 0x21a4b98
name = "g_pAnimationSystem"
size = 0x8

[0x21a4ba0]
addr = 0x21a4ba0
name = "g_pAnimationSystemUtils"
size = 0x1

[0x21a4ba8]
addr = 0x21a4ba8
name = "g_pTestScriptMgr"
size = 0x8

[0x21a4bb0]
addr = 0x21a4bb0
name = "g_pModelProcessingServices"
size = 0x1

[0x21a4bb8]
addr = 0x21a4bb8
name = "g_pLocalize"
size = 0x1

[0x21a4bc0]
addr = 0x21a4bc0
name = "g_pMaterialUtils"
size = 0x1

[0x21a4bc8]
addr = 0x21a4bc8
name = "g_pFontManager"
size = 0x8

[0x21a4bd0]
addr = 0x21a4bd0
name = "g_pTextLayout"
size = 0x1

[0x21a4bd8]
addr = 0x21a4bd8
name = "g_pAssetRenameSystem"
size = 0x1

[0x21a4be0]
addr = 0x21a4be0
name = "g_pAssetPreviewSystem"
size = 0x1

[0x21a4be8]
addr = 0x21a4be8
name = "g_pAssetBrowserSystem"
size = 0x1

[0x21a4bf0]
addr = 0x21a4bf0
name = "g_pRenderDeviceMgr"
size = 0x1

[0x21a4bf8]
addr = 0x21a4bf8
name = "g_pFileSystem"
size = 0x8

[0x21a4c00]
addr = 0x21a4c00
name = "g_pAsyncFileSystem"
size = 0x1

[0x21a4c08]
addr = 0x21a4c08
name = "g_pAssetSystem"
size = 0x8

[0x21a4c10]
addr = 0x21a4c10
name = "g_pAssetSystemTest"
size = 0x1

[0x21a4c18]
addr = 0x21a4c18
name = "g_pPropertyEditorSystem"
size = 0x1

[0x21a4c20]
addr = 0x21a4c20
name = "g_pSchemaSystem"
size = 0x8

[0x21a4c28]
addr = 0x21a4c28
name = "g_pResourceCompilerSystem"
size = 0x1

[0x21a4c30]
addr = 0x21a4c30
name = "g_pResourceSystem"
size = 0x8

[0x21a4c38]
addr = 0x21a4c38
name = "g_pResourceHandleUtils"
size = 0x8

[0x21a4c40]
addr = 0x21a4c40
name = "g_pResourceManifestRegistry"
size = 0x8

[0x21a4c48]
addr = 0x21a4c48
name = "g_pMaterialSystem2"
size = 0x8

[0x21a4c50]
addr = 0x21a4c50
name = "g_pPostProcessingSystem"
size = 0x1

[0x21a4c58]
addr = 0x21a4c58
name = "g_pInputSystem"
size = 0x8

[0x21a4c60]
addr = 0x21a4c60
name = "g_pInputStackSystem"
size = 0x8

[0x21a4c68]
addr = 0x21a4c68
name = "g_pVP4"
size = 0x1

[0x21a4c70]
addr = 0x21a4c70
name = "g_pMatchFramework"
size = 0x8

[0x21a4c78]
addr = 0x21a4c78
name = "g_pVConComm"
size = 0x8
